name: Deploy Snapshot to Maven Central

on:
  push:
    branches: [main, 1.1.x 1.0.x]

jobs:
  release:
    if: github.repository == 'jdbc-observations/datasource-micrometer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish snapshots
        run: ./mvnw -B javadoc:jar source:jar deploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
